# import lib

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
start_path = "./debug_test1_new"  # Update this path to your new output directory
results_file = f"{start_path}/summary.csv"
ocr_file = f"{start_path}/ocr_results.csv"
# Load results
results_df = pd.read_csv(results_file)
ocr_df = pd.read_csv(ocr_file)

In [20]:
len(results_df), len(ocr_df)

(33, 33)

In [21]:
dni_zone = results_df.copy()
ocr_results = ocr_df.copy()

In [52]:
print(f"max page: {dni_zone['page'].max()}")
print(f"num unique DNI predected:{ocr_results['predicted_dni'].nunique()}")
print(f"num of duplicate predicted DNI:{ocr_results['predicted_dni'].duplicated().sum()}")

max page: 112
num unique DNI predected:29
num of duplicate predicted DNI:4

In [22]:
dni_zone.head()

,page,dni_anchor_x0,dni_anchor_y0,dni_anchor_x1,dni_anchor_y1,annotated_image,box_1,box_2,box_3,box_4,box_5,box_6,box_7,box_8,box_9
0,1,295,282,381,346,/home/ariouich/Bureau/valencia/Madrina/Asisten...,"(382, 240, 488, 346)","(488, 240, 596, 347)","(596, 240, 703, 348)","(703, 240, 810, 349)","(810, 240, 919, 350)","(919, 240, 1026, 351)","(1026, 240, 1132, 351)","(1132, 240, 1239, 352)","(1239, 240, 1346, 353)"
1,7,244,300,385,344,/home/ariouich/Bureau/valencia/Madrina/Asisten...,"(387, 238, 493, 344)","(493, 238, 601, 345)","(601, 238, 708, 346)","(708, 238, 815, 347)","(815, 238, 924, 348)","(924, 238, 1031, 349)","(1031, 238, 1137, 351)","(1137, 238, 1243, 352)","(1243, 238, 1351, 352)"
2,13,294,300,0,314,/home/ariouich/Bureau/valencia/Madrina/Asisten...,"(371, 267, 140, 358)","(371, 267, 475, 359)","(477, 267, 584, 359)","(584, 267, 692, 359)","(692, 267, 799, 360)","(799, 267, 908, 360)","(908, 267, 1014, 360)","(1014, 267, 1120, 360)","(1120, 267, 1227, 361)"
3,19,294,300,384,310,/home/ariouich/Bureau/valencia/Madrina/Asisten...,"(385, 245, 491, 353)","(491, 245, 599, 352)","(599, 245, 706, 353)","(706, 245, 813, 354)","(813, 245, 922, 355)","(922, 245, 1029, 356)","(1029, 245, 1135, 357)","(1135, 245, 1241, 358)","(1241, 245, 1348, 358)"
4,25,255,210,397,317,/home/ariouich/Bureau/valencia/Madrina/Asisten...,"(397, 212, 503, 317)","(503, 212, 610, 318)","(610, 212, 718, 320)","(718, 212, 825, 321)","(825, 212, 934, 323)","(934, 212, 1041, 324)","(1041, 212, 1147, 325)","(1147, 212, 1260, 327)","(1260, 212, 1361, 328)"

In [23]:
ocr_results.head()

,page,predicted_dni,prediction_digits,exception_occurred,ground_truth_dni,exact_match,best_student_dni,best_student_nombre,best_student_apellidos,best_student_ratio
0,1,474799592,474799592,False,NaN,NaN,47479954,Pablo,Gargallo Valera,0.777778
1,7,529272532,529272532,False,NaN,NaN,39937253,Izan,Lopez Macia,0.555556
2,13,148729352,148729352,True,NaN,NaN,48729372,Javier,Sánchez Flor,0.777778
3,19,218023552,218023552,False,NaN,NaN,21802355,Jorge,Garcia Cortés,0.888889
4,25,62863895,62863895,False,NaN,NaN,6286789,Emma,Sánchez Silaghi,0.750000

In [45]:
df = pd.read_csv(
    "/home/ariouich/Bureau/valencia/Madrina/OriginalVersion/P1_nov_para_jefferson/students_list.csv",
    encoding='latin-1',
    sep=';'
)

In [41]:
df.head()

,DNI,Nombre,Grupo,Titulación,Tipo de Matrícula,Convocatoria,Comentario Profesor,Condición,Nota final,Nota sin restricciones,...,Rec. P2,Rec. P1,Parcial 2,Parcial 1,CT_01,Poliformat (sobre 10),Prácticas (sobre 10),Retornables (sobre 10),ACTA,Unnamed: 21
0,20851815,"Abril Revert, Borja",1PARS3,190 Grado en Ingeniería de Tecnologías y Servi...,Ordinaria,1.0,NaN,C Convocatoria confirmada,"9,38","9,38",...,NaN,NaN,"9,1","9,25",NaN,"9,84",10,"9,81","9,4",NaN
1,26665047,"Abu-Taha Sabsoub, Nader",B1,190 Grado en Ingeniería de Tecnologías y Servi...,Ordinaria,1.0,NaN,C Convocatoria confirmada,"5,9","5,9",...,NaN,NaN,"5,55","5,05",NaN,"7,14","8,94","4,34","5,9",NaN
2,49570057,"Acedo Marzo, Unai",B2,190 Grado en Ingeniería de Tecnologías y Servi...,Ordinaria,1.0,NaN,C Convocatoria confirmada,6,6,...,NaN,NaN,"3,8","6,9",NaN,"7,65","8,29","8,04",6,NaN
3,73606454,"Agustina García, Sol",A3,190 Grado en Ingeniería de Tecnologías y Servi...,Ordinaria,1.0,NaN,C Convocatoria confirmada,4,"4,71",...,NaN,NaN,"2,85","5,3",NaN,"6,76","6,48","6,71",4,NaN
4,51780631,"Ahuir Botella, Pau",A1,190 Grado en Ingeniería de Tecnologías y Servi...,Ordinaria,1.0,NaN,C Convocatoria confirmada,"7,58","7,58",...,NaN,NaN,"6,35","8,55",NaN,"6,82","9,9","6,89","7,6",NaN

In [43]:
print(f"Forme: {df.shape}")

Forme: (260, 22)

In [50]:
df_students_json = pd.read_json("./students.json")

In [51]:
df_students_json

,dni,nombre,apellidos
0,20851815,Borja,Abril Revert
1,26665047,Nader,Abu-Taha Sabsoub
2,49570057,Unai,Acedo Marzo
3,73606454,Sol,Agustina García
4,51780631,Pau,Ahuir Botella
...,...,...,...
255,Z807424,Filip Michal,Wolski
256,X7470664,Sandra,Yin
257,53947757,Marc,Zaragoza García
258,24421010,Jose,Zaragoza López
259,***Alumnes exportats: 259 - Columnes exportade...,,